#!/bin/bash
set -e

if [[ -n "$(docker ps -qaf 'name=parsec')" ]]; then
    docker restart parsec
else
    USER_UID=$(id -u)
    USER_GID=$(id -g)

    docker run --rm --name parsec \
        -e USER_UID=${USER_UID} \
        -e USER_GID=${USER_GID} \
        -e DISPLAY=unix:0.0 \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /run/user/${USER_UID}/pulse:/run/pulse:ro \
        --mount source=parsec_home,target=/home/parsec \
        --device=/dev/dri
        jfyne/parsec
fi

